import { registry } from "../registry";
import { ArmorCloth } from "./ArmorCloth";
import { ArmorLeather } from "./ArmorLeather";
import { ArmorMail } from "./ArmorMail";
import { ArmorPlate } from "./ArmorPlate";
import { LegsCloth } from "./LegsCloth";
import { LegsLeather } from "./LegsLeather";
import { LegsMail } from "./LegsMail";
import { LegsPlate } from "./LegsPlate";
import { BootsCloth } from "./BootsCloth";
import { BootsLeather } from "./BootsLeather";
import { BootsMail } from "./BootsMail";
import { BootsPlate } from "./BootsPlate";
import { ShouldersCloth } from "./ShouldersCloth";
import { ShouldersLeather } from "./ShouldersLeather";
import { ShouldersMail } from "./ShouldersMail";
import { ShouldersPlate } from "./ShouldersPlate";
import { GauntletsCloth } from "./GauntletsCloth";
import { GauntletsLeather } from "./GauntletsLeather";
import { GauntletsMail } from "./GauntletsMail";
import { GauntletsPlate } from "./GauntletsPlate";

registry.register(new ArmorCloth());
registry.register(new ArmorLeather());
registry.register(new ArmorMail());
registry.register(new ArmorPlate());
registry.register(new LegsCloth());
registry.register(new LegsLeather());
registry.register(new LegsMail());
registry.register(new LegsPlate());
registry.register(new BootsCloth());
registry.register(new BootsLeather());
registry.register(new BootsMail());
registry.register(new BootsPlate());
registry.register(new ShouldersCloth());
registry.register(new ShouldersLeather());
registry.register(new ShouldersMail());
registry.register(new ShouldersPlate());
registry.register(new GauntletsCloth());
registry.register(new GauntletsLeather());
registry.register(new GauntletsMail());
registry.register(new GauntletsPlate());
